version: '3.8'

services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: symfony_app
    volumes:
      - .:/var/www
    depends_on:
      db:
        condition: service_healthy
    environment:
      APP_ENV: dev
      APP_SECRET: unsecretomuylargoycomplejo
      DATABASE_URL: "mysql://symfony:symfony@db:3306/gestion_proveedores?serverVersion=8.0&charset=utf8mb4"

  nginx:
    image: nginx:alpine
    container_name: symfony_nginx
    ports:
      - "8080:80"
    volumes:
      - .:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: symfony_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: gestion_proveedores
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

volumes:
  db_data: